# Application server ID
passwordless.corpId = ce70c95d3aab4ed6ba3ee7a138581e58
passwordless.serverId = ce70c95d3aab4ed6ba3ee7a138581e58


# Application server key (Only displayed once when changed)
passwordless.serverKey = 8702094eca501c64


# URL to go to Simple UI screen (passwordless server - nginx)
passwordless.simpleAutopasswordUrl = http://192.168.0.8:8080


# Authentication server domain
passwordless.restCheckUrl = http://192.168.0.8:11040
e
rr
# Push request server to connect to Websocket
passwordless.pushConnectorUrl = ws:192.168.0.8:15010


# Passwordless Recommended Specifications (ID/Password login prohibited when registering Passwordless) - 1: Applied, 0: Not Applied
passwordless.recommend = 1
