# Application server ID
passwordless.corpId = df2f3fc8685240c3be42eaf8a1b9e53b
passwordless.serverId = df2f3fc8685240c3be42eaf8a1b9e53b


# Application server key (Only displayed once when changed)
passwordless.serverKey = a2789120a51fca64


# URL to go to Simple UI screen (passwordless server - nginx)
passwordless.simpleAutopasswordUrl = http://43.203.153.169:8080


# Authentication server domain
passwordless.restCheckUrl = http://43.203.153.169:11040


# Push request server to connect to Websocket
passwordless.pushConnectorUrl = ws:43.203.153.169:15010


# Passwordless Recommended Specifications (ID/Password login prohibited when registering Passwordless) - 1: Applied, 0: Not Applied
passwordless.recommend = 1
